"""The optional embedded C64 font (`render/c64font_data.py`).

Whether Commodore's glyph bitmaps belong in this repository is a judgement about
redistribution rather than a technical question, so the code is built to work
**either way** and these hold it to that. The module is generated by
`tools/embed_c64_font.py`; the tests pass whether or not anyone has run it.

The property that matters is reversibility: adding the file is the decision,
deleting it is the decision reversed, and neither touches anything else.
"""

from __future__ import annotations

import hashlib
import importlib
import os
import sys

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")

import pytest  # noqa: E402

from alien_remake import assets  # noqa: E402
from alien_remake.render import romfont  # noqa: E402


def _embedded():
    try:
        from alien_remake.render import c64font_data
    except ImportError:
        return None
    return c64font_data


def _hide_the_module(monkeypatch: pytest.MonkeyPatch) -> None:
    """Make `from . import c64font_data` fail the way a deleted file would.

    **Setting `sys.modules[...] = None` is not enough**, which is what these two
    tests did until a fresh install caught them: once the module has been
    imported it is also an *attribute* of the package, and `from . import X`
    finds it there. Locally the tests passed anyway because `find_c64_rom` found
    the archived VICE ROM and returned before the fallback was ever reached — so
    they were green without exercising the thing they were written for.
    """
    import alien_remake.render as render_pkg

    monkeypatch.setitem(sys.modules, "alien_remake.render.c64font_data", None)
    monkeypatch.delattr(render_pkg, "c64font_data", raising=False)


def test_absent_is_a_supported_state(monkeypatch: pytest.MonkeyPatch) -> None:
    """Without the module and without a ROM, `load()` returns None and the
    renderer uses SysFont — exactly as it did before the option existed."""
    monkeypatch.setattr(assets, "find_c64_rom", lambda name: None)
    _hide_the_module(monkeypatch)
    assert romfont.load() is None


def test_a_broken_table_degrades_rather_than_draws_nonsense(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A wrong-sized table would render garbage in place of every letter, which
    is worse than the fallback face."""
    class _Bad:
        @staticmethod
        def glyph_rom() -> bytes:
            return b"\x00" * 10

    import alien_remake.render as render_pkg

    monkeypatch.setattr(assets, "find_c64_rom", lambda name: None)
    monkeypatch.setitem(sys.modules, "alien_remake.render.c64font_data", _Bad)
    monkeypatch.setattr(render_pkg, "c64font_data", _Bad, raising=False)
    importlib.invalidate_caches()
    assert romfont.load() is None


def test_a_real_rom_still_wins(monkeypatch: pytest.MonkeyPatch) -> None:
    """The embedded table is the fallback, not the preference: someone who
    points at their own ROM gets theirs."""
    found = assets.find_c64_rom("chargen.bin")
    if found is None:
        pytest.skip("no chargen ROM on this machine")
    font = romfont.load()
    assert font is not None
    assert font._data == found.read_bytes()


# --- only when somebody has run the generator ------------------------------------

def test_the_embedded_table_is_the_right_size_and_matches_its_hash() -> None:
    module = _embedded()
    if module is None:
        pytest.skip("c64font_data is not present; that is a supported state")
    data = module.glyph_rom()
    assert len(data) == 4096
    assert hashlib.sha256(data).hexdigest() == module.SHA256, (
        "the published SHA does not match the bytes - regenerate it"
    )


def test_the_embedded_table_matches_a_real_rom() -> None:
    module = _embedded()
    found = assets.find_c64_rom("chargen.bin")
    if module is None or found is None:
        pytest.skip("needs both the embedded table and a ROM to compare")
    assert module.glyph_rom() == found.read_bytes()


def test_it_lives_in_exactly_one_file() -> None:
    """The reversibility guarantee: one deletion undoes it. If a second module
    ever starts carrying glyph bytes, this stops being true and the claim in
    the docstrings becomes false."""
    import subprocess

    tracked = subprocess.run(
        ["git", "ls-files", "src"], capture_output=True, text=True, check=True,
    ).stdout.split()
    carriers = [p for p in tracked if p.endswith("c64font_data.py")]
    assert len(carriers) <= 1, carriers


def test_the_generator_exists_and_says_how_to_undo_it() -> None:
    """Somebody finding this in a year should not have to work out how to take
    it back out."""
    import pathlib

    tool = pathlib.Path(__file__).resolve().parent.parent / "tools" / "embed_c64_font.py"
    assert tool.is_file()
    text = tool.read_text(encoding="utf-8")
    assert "to undo" in text
    assert "falls back" in text
