"""Generate `render/c64font_data.py` from a C64 character ROM you already have.

    python tools/embed_c64_font.py            # find a ROM the usual ways
    python tools/embed_c64_font.py chargen.bin

**Why this is a tool and not a committed file.** Whether Commodore's glyph
bitmaps belong in this repository is a judgement about redistribution, not a
technical question, so the code is built to work either way: `romfont` imports
`c64font_data` defensively and falls back to the system monospace face when it
is absent, which is exactly what it did before the option existed. Running this
is the decision; deleting the file it writes is the decision reversed. Nothing
else needs touching in either direction.

**Why the whole table rather than the glyphs that get drawn.** Measured: the 94
glyphs actually drawn across every front-end screen include **25 of the 26
letters**, so a partial capture takes essentially the whole typeface anyway -
what it leaves behind is the PETSCII box-drawing set nobody prints. In exchange
it buys a table that develops holes the moment a new string needs a glyph nobody
anticipated, and the font changing mid-sentence reads as a bug. Complete is more
honest about what was taken and more robust.

**Why not a lookalike.** A bitmap font *is* its bitmaps. The front-end screens
are pixel-exact reconstructions of a real machine's output (D-047/D-065); a
redrawn approximation would make them nearly-right, which is the one thing this
project does not do.
"""

from __future__ import annotations

import base64
import hashlib
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from alien_remake import assets  # noqa: E402

ROM_BYTES = 4096
OUT = (
    Path(__file__).resolve().parent.parent
    / "src" / "alien_remake" / "render" / "c64font_data.py"
)

HEADER = '''"""The C64 character ROM's glyph bitmaps, so the loader screens look right.

**Generated by `tools/embed_c64_font.py`. Not written by hand.**

This file is the one place Commodore's data lives in this repository, and it is
deliberately the only one. Delete it and the game still runs: `romfont` falls
back to the system monospace face exactly as it did before this existed, and the
tests prove that rather than asserting it. Keeping it in a module of its own is
what makes the decision to include it reversible with a single deletion.

What it is
----------
4096 bytes: two banks of 256 glyphs, eight rows each, MSB-left. Bank 0 is
unshifted (uppercase + graphics), bank 1 shifted (lower + upper). It is the
standard `chargen-901225-01` image, and the SHA-256 below is published so a
reader can check it against a copy of their own rather than trust this one.

Provenance
----------
Commodore Business Machines, 1982. Included for the accuracy of a
reconstruction. The game's own charset, the disk image and everything else this
remake needs still come from the player's own copy - see the README.
"""

from __future__ import annotations

import base64

#: `sha256` of the decoded bytes, so a reader can verify this against a ROM of
#: their own instead of taking it on trust.
SHA256 = "__SHA__"

_DATA = (
__ROWS__
)


def glyph_rom() -> bytes:
    """The 4096 bytes, decoded. Cheap enough not to cache."""
    return base64.b64decode("".join(_DATA))
'''


def main(argv: list[str]) -> int:
    if argv:
        source: Path | None = Path(argv[0])
    else:
        source = assets.find_c64_rom("chargen.bin")
    if source is None or not source.is_file():
        print(
            "no chargen ROM found. Install VICE (any C64 emulator ships one), "
            "or pass the path:\n"
            "    python tools/embed_c64_font.py path/to/chargen-901225-01.bin",
            file=sys.stderr,
        )
        return 2

    data = source.read_bytes()
    if len(data) != ROM_BYTES:
        print(
            f"{source} is {len(data)} bytes; a C64 chargen ROM is {ROM_BYTES}. "
            "Refusing to embed it - a wrong table draws nonsense, which is "
            "worse than the fallback font.",
            file=sys.stderr,
        )
        return 2

    rows = "\n".join(
        '    "' + line + '"'
        for line in textwrap.wrap(base64.b64encode(data).decode(), 72)
    )
    OUT.write_text(
        HEADER.replace("__SHA__", hashlib.sha256(data).hexdigest())
              .replace("__ROWS__", rows),
        encoding="utf-8",
        newline="",
    )
    print(f"wrote {OUT.relative_to(OUT.parents[3])} from {source}")
    print("the loader screens will now use the real C64 font.")
    print("to undo: delete that file. Nothing else refers to it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
